[2025-04-30T02:52:43.955+0000] {processor.py:186} INFO - Started process (PID=78) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T02:52:43.958+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T02:52:44.012+0000] {logging_mixin.py:190} INFO - [2025-04-30T02:52:44.011+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T02:52:44.556+0000] {processor.py:925} INFO - DAG(s) 'etl_csv_pipeline_v2' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T02:52:44.858+0000] {logging_mixin.py:190} INFO - [2025-04-30T02:52:44.856+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-30T02:52:45.099+0000] {logging_mixin.py:190} INFO - [2025-04-30T02:52:45.098+0000] {dag.py:4180} INFO - Setting next_dagrun for etl_csv_pipeline_v2 to None, run_after=None
[2025-04-30T02:52:45.601+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 1.720 seconds
[2025-04-30T02:53:57.518+0000] {processor.py:186} INFO - Started process (PID=155) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T02:53:57.520+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T02:53:57.556+0000] {logging_mixin.py:190} INFO - [2025-04-30T02:53:57.555+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T02:53:57.925+0000] {processor.py:925} INFO - DAG(s) 'etl_csv_pipeline_v2' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T02:53:58.136+0000] {logging_mixin.py:190} INFO - [2025-04-30T02:53:58.135+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-30T02:53:58.318+0000] {logging_mixin.py:190} INFO - [2025-04-30T02:53:58.317+0000] {dag.py:4180} INFO - Setting next_dagrun for etl_csv_pipeline_v2 to None, run_after=None
[2025-04-30T02:53:58.695+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 1.238 seconds
[2025-04-30T02:54:39.787+0000] {processor.py:186} INFO - Started process (PID=210) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T02:54:39.899+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T02:54:39.949+0000] {logging_mixin.py:190} INFO - [2025-04-30T02:54:39.948+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T02:54:40.381+0000] {processor.py:925} INFO - DAG(s) 'etl_csv_pipeline_v2' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T02:54:40.520+0000] {logging_mixin.py:190} INFO - [2025-04-30T02:54:40.519+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-30T02:54:40.620+0000] {logging_mixin.py:190} INFO - [2025-04-30T02:54:40.620+0000] {dag.py:4180} INFO - Setting next_dagrun for etl_csv_pipeline_v2 to None, run_after=None
[2025-04-30T02:54:40.791+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 1.166 seconds
[2025-04-30T02:55:14.204+0000] {processor.py:186} INFO - Started process (PID=272) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T02:55:14.227+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T02:55:14.276+0000] {logging_mixin.py:190} INFO - [2025-04-30T02:55:14.231+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T02:55:15.496+0000] {processor.py:925} INFO - DAG(s) 'etl_csv_pipeline_v2' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T02:55:15.657+0000] {logging_mixin.py:190} INFO - [2025-04-30T02:55:15.648+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-30T02:55:15.730+0000] {logging_mixin.py:190} INFO - [2025-04-30T02:55:15.730+0000] {dag.py:4180} INFO - Setting next_dagrun for etl_csv_pipeline_v2 to None, run_after=None
[2025-04-30T02:55:15.803+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 1.694 seconds
[2025-04-30T02:55:47.058+0000] {processor.py:186} INFO - Started process (PID=330) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T02:55:47.060+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T02:55:47.065+0000] {logging_mixin.py:190} INFO - [2025-04-30T02:55:47.064+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T02:55:47.176+0000] {processor.py:925} INFO - DAG(s) 'etl_csv_pipeline_v2' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T02:55:47.230+0000] {logging_mixin.py:190} INFO - [2025-04-30T02:55:47.230+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-30T02:55:47.267+0000] {logging_mixin.py:190} INFO - [2025-04-30T02:55:47.267+0000] {dag.py:4180} INFO - Setting next_dagrun for etl_csv_pipeline_v2 to None, run_after=None
[2025-04-30T02:55:47.325+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.281 seconds
[2025-04-30T02:56:18.362+0000] {processor.py:186} INFO - Started process (PID=374) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T02:56:18.378+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T02:56:18.389+0000] {logging_mixin.py:190} INFO - [2025-04-30T02:56:18.389+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T02:56:18.531+0000] {processor.py:925} INFO - DAG(s) 'etl_csv_pipeline_v2' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T02:56:18.894+0000] {logging_mixin.py:190} INFO - [2025-04-30T02:56:18.894+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-30T02:56:19.043+0000] {logging_mixin.py:190} INFO - [2025-04-30T02:56:19.042+0000] {dag.py:4180} INFO - Setting next_dagrun for etl_csv_pipeline_v2 to None, run_after=None
[2025-04-30T02:56:19.193+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.866 seconds
[2025-04-30T02:56:53.516+0000] {processor.py:186} INFO - Started process (PID=433) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T02:56:53.524+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T02:56:53.553+0000] {logging_mixin.py:190} INFO - [2025-04-30T02:56:53.552+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T02:56:53.837+0000] {processor.py:925} INFO - DAG(s) 'etl_csv_pipeline_v2' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T02:56:53.941+0000] {logging_mixin.py:190} INFO - [2025-04-30T02:56:53.940+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-30T02:56:54.015+0000] {logging_mixin.py:190} INFO - [2025-04-30T02:56:54.014+0000] {dag.py:4180} INFO - Setting next_dagrun for etl_csv_pipeline_v2 to None, run_after=None
[2025-04-30T02:56:54.159+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.681 seconds
[2025-04-30T02:57:25.475+0000] {processor.py:186} INFO - Started process (PID=497) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T02:57:25.477+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T02:57:25.484+0000] {logging_mixin.py:190} INFO - [2025-04-30T02:57:25.483+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T02:57:25.606+0000] {processor.py:925} INFO - DAG(s) 'etl_csv_pipeline_v2' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T02:57:25.652+0000] {logging_mixin.py:190} INFO - [2025-04-30T02:57:25.652+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-30T02:57:25.689+0000] {logging_mixin.py:190} INFO - [2025-04-30T02:57:25.688+0000] {dag.py:4180} INFO - Setting next_dagrun for etl_csv_pipeline_v2 to None, run_after=None
[2025-04-30T02:57:25.736+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.275 seconds
[2025-04-30T02:57:56.510+0000] {processor.py:186} INFO - Started process (PID=560) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T02:57:56.515+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T02:57:56.521+0000] {logging_mixin.py:190} INFO - [2025-04-30T02:57:56.520+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T02:57:56.640+0000] {processor.py:925} INFO - DAG(s) 'etl_csv_pipeline_v2' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T02:57:56.800+0000] {logging_mixin.py:190} INFO - [2025-04-30T02:57:56.793+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-30T02:57:56.874+0000] {logging_mixin.py:190} INFO - [2025-04-30T02:57:56.874+0000] {dag.py:4180} INFO - Setting next_dagrun for etl_csv_pipeline_v2 to None, run_after=None
[2025-04-30T02:57:57.003+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.511 seconds
[2025-04-30T02:58:27.621+0000] {processor.py:186} INFO - Started process (PID=623) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T02:58:27.642+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T02:58:27.655+0000] {logging_mixin.py:190} INFO - [2025-04-30T02:58:27.654+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T02:58:28.161+0000] {processor.py:925} INFO - DAG(s) 'etl_csv_pipeline_v2' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T02:58:28.251+0000] {logging_mixin.py:190} INFO - [2025-04-30T02:58:28.250+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-30T02:58:28.292+0000] {logging_mixin.py:190} INFO - [2025-04-30T02:58:28.291+0000] {dag.py:4180} INFO - Setting next_dagrun for etl_csv_pipeline_v2 to None, run_after=None
[2025-04-30T02:58:28.379+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.779 seconds
[2025-04-30T02:58:58.589+0000] {processor.py:186} INFO - Started process (PID=693) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T02:58:58.591+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T02:58:58.595+0000] {logging_mixin.py:190} INFO - [2025-04-30T02:58:58.594+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T02:58:58.736+0000] {processor.py:925} INFO - DAG(s) 'etl_csv_pipeline_v2' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T02:58:58.801+0000] {logging_mixin.py:190} INFO - [2025-04-30T02:58:58.800+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-30T02:58:58.865+0000] {logging_mixin.py:190} INFO - [2025-04-30T02:58:58.864+0000] {dag.py:4180} INFO - Setting next_dagrun for etl_csv_pipeline_v2 to None, run_after=None
[2025-04-30T02:58:58.939+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.362 seconds
[2025-04-30T02:59:29.825+0000] {processor.py:186} INFO - Started process (PID=758) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T02:59:29.828+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T02:59:29.834+0000] {logging_mixin.py:190} INFO - [2025-04-30T02:59:29.833+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T02:59:29.986+0000] {processor.py:925} INFO - DAG(s) 'etl_csv_pipeline_v2' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T02:59:30.035+0000] {logging_mixin.py:190} INFO - [2025-04-30T02:59:30.034+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-30T02:59:30.072+0000] {logging_mixin.py:190} INFO - [2025-04-30T02:59:30.071+0000] {dag.py:4180} INFO - Setting next_dagrun for etl_csv_pipeline_v2 to None, run_after=None
[2025-04-30T02:59:30.126+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.316 seconds
[2025-04-30T03:00:00.649+0000] {processor.py:186} INFO - Started process (PID=821) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:00:00.651+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T03:00:00.660+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:00:00.659+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:00:00.774+0000] {processor.py:925} INFO - DAG(s) 'etl_csv_pipeline_v2' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:00:00.891+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:00:00.891+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-30T03:00:01.003+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:00:01.002+0000] {dag.py:4180} INFO - Setting next_dagrun for etl_csv_pipeline_v2 to None, run_after=None
[2025-04-30T03:00:01.154+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.520 seconds
[2025-04-30T03:00:32.195+0000] {processor.py:186} INFO - Started process (PID=885) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:00:32.197+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T03:00:32.205+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:00:32.205+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:00:32.302+0000] {processor.py:925} INFO - DAG(s) 'etl_csv_pipeline_v2' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:00:32.369+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:00:32.369+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-30T03:00:32.420+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:00:32.419+0000] {dag.py:4180} INFO - Setting next_dagrun for etl_csv_pipeline_v2 to None, run_after=None
[2025-04-30T03:00:32.474+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.300 seconds
[2025-04-30T03:01:02.595+0000] {processor.py:186} INFO - Started process (PID=950) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:01:02.597+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T03:01:02.602+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:01:02.601+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:01:02.676+0000] {processor.py:925} INFO - DAG(s) 'etl_csv_pipeline_v2' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:01:02.708+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:01:02.708+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-30T03:01:02.734+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:01:02.733+0000] {dag.py:4180} INFO - Setting next_dagrun for etl_csv_pipeline_v2 to None, run_after=None
[2025-04-30T03:01:02.772+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.187 seconds
[2025-04-30T03:01:33.195+0000] {processor.py:186} INFO - Started process (PID=1014) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:01:33.197+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T03:01:33.200+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:01:33.200+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:01:33.358+0000] {processor.py:925} INFO - DAG(s) 'etl_csv_pipeline_v2' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:01:33.434+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:01:33.434+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-30T03:01:33.473+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:01:33.472+0000] {dag.py:4180} INFO - Setting next_dagrun for etl_csv_pipeline_v2 to None, run_after=None
[2025-04-30T03:01:33.524+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.341 seconds
[2025-04-30T03:04:14.254+0000] {processor.py:186} INFO - Started process (PID=65) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:04:14.278+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T03:04:14.290+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:04:14.290+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:04:14.609+0000] {processor.py:925} INFO - DAG(s) 'etl_csv_pipeline_v2' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:04:14.775+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:04:14.774+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-30T03:04:14.866+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:04:14.866+0000] {dag.py:4180} INFO - Setting next_dagrun for etl_csv_pipeline_v2 to None, run_after=None
[2025-04-30T03:04:14.969+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.747 seconds
[2025-04-30T03:04:45.670+0000] {processor.py:186} INFO - Started process (PID=129) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:04:45.673+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T03:04:45.686+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:04:45.678+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:04:45.882+0000] {processor.py:925} INFO - DAG(s) 'etl_csv_pipeline_v2' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:04:45.972+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:04:45.972+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-30T03:04:46.045+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:04:46.044+0000] {dag.py:4180} INFO - Setting next_dagrun for etl_csv_pipeline_v2 to None, run_after=None
[2025-04-30T03:04:46.163+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.515 seconds
[2025-04-30T03:05:16.886+0000] {processor.py:186} INFO - Started process (PID=193) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:05:16.888+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T03:05:16.892+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:05:16.891+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:05:17.150+0000] {processor.py:925} INFO - DAG(s) 'etl_csv_pipeline_v2' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:05:17.198+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:05:17.198+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-30T03:05:17.225+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:05:17.224+0000] {dag.py:4180} INFO - Setting next_dagrun for etl_csv_pipeline_v2 to None, run_after=None
[2025-04-30T03:05:17.260+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.386 seconds
[2025-04-30T03:05:47.512+0000] {processor.py:186} INFO - Started process (PID=257) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:05:47.514+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T03:05:47.529+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:05:47.528+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:05:47.599+0000] {processor.py:925} INFO - DAG(s) 'etl_csv_pipeline_v2' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:05:47.635+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:05:47.635+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-30T03:05:47.663+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:05:47.662+0000] {dag.py:4180} INFO - Setting next_dagrun for etl_csv_pipeline_v2 to None, run_after=None
[2025-04-30T03:05:47.723+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.231 seconds
[2025-04-30T03:06:18.394+0000] {processor.py:186} INFO - Started process (PID=327) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:06:18.400+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T03:06:18.411+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:06:18.408+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:06:18.576+0000] {processor.py:925} INFO - DAG(s) 'etl_csv_pipeline_v2' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:06:18.646+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:06:18.646+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-30T03:06:18.677+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:06:18.676+0000] {dag.py:4180} INFO - Setting next_dagrun for etl_csv_pipeline_v2 to None, run_after=None
[2025-04-30T03:06:18.729+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.354 seconds
[2025-04-30T03:06:48.813+0000] {processor.py:186} INFO - Started process (PID=391) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:06:48.815+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T03:06:48.819+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:06:48.818+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:06:48.877+0000] {processor.py:925} INFO - DAG(s) 'etl_csv_pipeline_v2' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:06:48.903+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:06:48.903+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-30T03:06:48.925+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:06:48.925+0000] {dag.py:4180} INFO - Setting next_dagrun for etl_csv_pipeline_v2 to None, run_after=None
[2025-04-30T03:06:48.966+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.165 seconds
[2025-04-30T03:07:19.781+0000] {processor.py:186} INFO - Started process (PID=456) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:07:19.783+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T03:07:19.791+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:07:19.790+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:07:19.924+0000] {processor.py:925} INFO - DAG(s) 'etl_csv_pipeline_v2' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:07:19.986+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:07:19.986+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-30T03:07:20.040+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:07:20.039+0000] {dag.py:4180} INFO - Setting next_dagrun for etl_csv_pipeline_v2 to None, run_after=None
[2025-04-30T03:07:20.079+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.314 seconds
[2025-04-30T03:07:50.960+0000] {processor.py:186} INFO - Started process (PID=519) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:07:50.964+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T03:07:50.968+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:07:50.967+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:07:51.041+0000] {processor.py:925} INFO - DAG(s) 'etl_csv_pipeline_v2' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:07:51.074+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:07:51.074+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-30T03:07:51.098+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:07:51.098+0000] {dag.py:4180} INFO - Setting next_dagrun for etl_csv_pipeline_v2 to None, run_after=None
[2025-04-30T03:07:51.136+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.186 seconds
[2025-04-30T03:08:21.621+0000] {processor.py:186} INFO - Started process (PID=583) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:08:21.623+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T03:08:21.629+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:08:21.628+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:08:21.774+0000] {processor.py:925} INFO - DAG(s) 'etl_csv_pipeline_v2' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:08:21.827+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:08:21.827+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-30T03:08:21.859+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:08:21.859+0000] {dag.py:4180} INFO - Setting next_dagrun for etl_csv_pipeline_v2 to None, run_after=None
[2025-04-30T03:08:21.928+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.319 seconds
[2025-04-30T03:08:52.482+0000] {processor.py:186} INFO - Started process (PID=647) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:08:52.484+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T03:08:52.496+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:08:52.492+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:08:52.612+0000] {processor.py:925} INFO - DAG(s) 'etl_csv_pipeline_v2' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:08:52.662+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:08:52.661+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-30T03:08:52.697+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:08:52.696+0000] {dag.py:4180} INFO - Setting next_dagrun for etl_csv_pipeline_v2 to None, run_after=None
[2025-04-30T03:08:52.777+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.307 seconds
[2025-04-30T03:09:23.093+0000] {processor.py:186} INFO - Started process (PID=712) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:09:23.095+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T03:09:23.100+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:09:23.099+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:09:23.208+0000] {processor.py:925} INFO - DAG(s) 'etl_csv_pipeline_v2' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:09:23.254+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:09:23.253+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-30T03:09:23.286+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:09:23.285+0000] {dag.py:4180} INFO - Setting next_dagrun for etl_csv_pipeline_v2 to None, run_after=None
[2025-04-30T03:09:23.335+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.251 seconds
[2025-04-30T03:09:54.097+0000] {processor.py:186} INFO - Started process (PID=775) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:09:54.101+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T03:09:54.113+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:09:54.113+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:09:54.706+0000] {processor.py:925} INFO - DAG(s) 'etl_csv_pipeline_v2' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:09:54.800+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:09:54.799+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-30T03:09:54.913+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:09:54.913+0000] {dag.py:4180} INFO - Setting next_dagrun for etl_csv_pipeline_v2 to None, run_after=None
[2025-04-30T03:09:55.074+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.999 seconds
[2025-04-30T03:10:25.368+0000] {processor.py:186} INFO - Started process (PID=839) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:10:25.372+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T03:10:25.400+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:10:25.400+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:10:25.665+0000] {processor.py:925} INFO - DAG(s) 'etl_csv_pipeline_v2' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:10:25.711+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:10:25.710+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-30T03:10:25.740+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:10:25.740+0000] {dag.py:4180} INFO - Setting next_dagrun for etl_csv_pipeline_v2 to None, run_after=None
[2025-04-30T03:10:25.780+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.433 seconds
[2025-04-30T03:10:58.286+0000] {processor.py:186} INFO - Started process (PID=890) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:10:58.288+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T03:10:58.294+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:10:58.294+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:10:58.406+0000] {processor.py:925} INFO - DAG(s) 'etl_csv_pipeline_v2' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:10:58.456+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:10:58.455+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-30T03:10:58.493+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:10:58.492+0000] {dag.py:4180} INFO - Setting next_dagrun for etl_csv_pipeline_v2 to None, run_after=None
[2025-04-30T03:10:58.636+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.362 seconds
[2025-04-30T03:11:28.805+0000] {processor.py:186} INFO - Started process (PID=953) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:11:28.808+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T03:11:28.814+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:11:28.813+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:11:28.898+0000] {processor.py:925} INFO - DAG(s) 'etl_csv_pipeline_v2' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:11:28.943+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:11:28.943+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-30T03:11:28.973+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:11:28.973+0000] {dag.py:4180} INFO - Setting next_dagrun for etl_csv_pipeline_v2 to None, run_after=None
[2025-04-30T03:11:29.025+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.233 seconds
[2025-04-30T03:11:59.122+0000] {processor.py:186} INFO - Started process (PID=1017) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:11:59.123+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T03:11:59.127+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:11:59.126+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:11:59.189+0000] {processor.py:925} INFO - DAG(s) 'etl_csv_pipeline_v2' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:11:59.216+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:11:59.216+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-30T03:11:59.241+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:11:59.240+0000] {dag.py:4180} INFO - Setting next_dagrun for etl_csv_pipeline_v2 to None, run_after=None
[2025-04-30T03:11:59.276+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.162 seconds
[2025-04-30T03:12:30.467+0000] {processor.py:186} INFO - Started process (PID=1072) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:12:30.469+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T03:12:30.483+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:12:30.482+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:12:30.656+0000] {processor.py:925} INFO - DAG(s) 'etl_csv_pipeline_v2' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:12:30.713+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:12:30.712+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-30T03:12:30.776+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:12:30.776+0000] {dag.py:4180} INFO - Setting next_dagrun for etl_csv_pipeline_v2 to None, run_after=None
[2025-04-30T03:12:30.857+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.408 seconds
[2025-04-30T03:13:01.490+0000] {processor.py:186} INFO - Started process (PID=1136) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:13:01.492+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T03:13:01.496+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:13:01.496+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:13:01.574+0000] {processor.py:925} INFO - DAG(s) 'etl_csv_pipeline_v2' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:13:01.620+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:13:01.620+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-30T03:13:01.655+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:13:01.655+0000] {dag.py:4180} INFO - Setting next_dagrun for etl_csv_pipeline_v2 to None, run_after=None
[2025-04-30T03:13:01.702+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.223 seconds
[2025-04-30T03:13:32.323+0000] {processor.py:186} INFO - Started process (PID=1196) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:13:32.325+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T03:13:32.329+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:13:32.329+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:13:32.394+0000] {processor.py:925} INFO - DAG(s) 'etl_csv_pipeline_v2' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:13:32.426+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:13:32.425+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-30T03:13:32.453+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:13:32.453+0000] {dag.py:4180} INFO - Setting next_dagrun for etl_csv_pipeline_v2 to None, run_after=None
[2025-04-30T03:13:32.486+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.172 seconds
[2025-04-30T03:14:04.930+0000] {processor.py:186} INFO - Started process (PID=1252) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:14:04.946+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T03:14:04.956+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:14:04.956+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:14:05.214+0000] {processor.py:925} INFO - DAG(s) 'etl_csv_pipeline_v2' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:14:05.333+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:14:05.332+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-30T03:14:05.454+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:14:05.452+0000] {dag.py:4180} INFO - Setting next_dagrun for etl_csv_pipeline_v2 to None, run_after=None
[2025-04-30T03:14:05.585+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.711 seconds
[2025-04-30T03:17:51.556+0000] {processor.py:186} INFO - Started process (PID=68) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:17:51.572+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T03:17:51.579+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:17:51.577+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:17:51.635+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:17:51.623+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 9, in <module>
    from clean_data import clean_data
  File "/opt/airflow/scripts/clean_data.py", line 5, in <module>
    from utils.parsers import parse_to_float
ModuleNotFoundError: No module named 'utils.parsers'
[2025-04-30T03:17:51.639+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:17:51.707+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.173 seconds
[2025-04-30T03:18:22.098+0000] {processor.py:186} INFO - Started process (PID=140) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:18:22.105+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T03:18:22.110+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:18:22.109+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:18:22.205+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:18:22.193+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 9, in <module>
    from clean_data import clean_data
  File "/opt/airflow/scripts/clean_data.py", line 5, in <module>
    from utils.parsers import parse_to_float
ModuleNotFoundError: No module named 'utils.parsers'
[2025-04-30T03:18:22.212+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:18:22.261+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.174 seconds
[2025-04-30T03:18:52.532+0000] {processor.py:186} INFO - Started process (PID=204) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:18:52.533+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T03:18:52.535+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:18:52.534+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:18:52.567+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:18:52.561+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 9, in <module>
    from clean_data import clean_data
  File "/opt/airflow/scripts/clean_data.py", line 5, in <module>
    from utils.parsers import parse_to_float
ModuleNotFoundError: No module named 'utils.parsers'
[2025-04-30T03:18:52.569+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:18:52.602+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.078 seconds
[2025-04-30T03:19:23.042+0000] {processor.py:186} INFO - Started process (PID=268) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:19:23.043+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T03:19:23.045+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:19:23.044+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:19:23.094+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:19:23.082+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 9, in <module>
    from clean_data import clean_data
  File "/opt/airflow/scripts/clean_data.py", line 5, in <module>
    from utils.parsers import parse_to_float
ModuleNotFoundError: No module named 'utils.parsers'
[2025-04-30T03:19:23.098+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:19:23.126+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.094 seconds
[2025-04-30T03:19:54.005+0000] {processor.py:186} INFO - Started process (PID=332) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:19:54.020+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T03:19:54.023+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:19:54.023+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:19:54.169+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:19:54.156+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 9, in <module>
    from clean_data import clean_data
  File "/opt/airflow/scripts/clean_data.py", line 5, in <module>
    from utils.parsers import parse_to_float
ModuleNotFoundError: No module named 'utils.parsers'
[2025-04-30T03:19:54.174+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:19:54.220+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.234 seconds
[2025-04-30T03:20:24.877+0000] {processor.py:186} INFO - Started process (PID=396) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:20:24.879+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T03:20:24.881+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:20:24.880+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:20:24.920+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:20:24.913+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 9, in <module>
    from clean_data import clean_data
  File "/opt/airflow/scripts/clean_data.py", line 5, in <module>
    from utils.parsers import parse_to_float
ModuleNotFoundError: No module named 'utils.parsers'
[2025-04-30T03:20:24.923+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:20:24.958+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.088 seconds
[2025-04-30T03:20:55.137+0000] {processor.py:186} INFO - Started process (PID=460) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:20:55.138+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T03:20:55.140+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:20:55.140+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:20:55.181+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:20:55.172+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 9, in <module>
    from clean_data import clean_data
  File "/opt/airflow/scripts/clean_data.py", line 5, in <module>
    from utils.parsers import parse_to_float
ModuleNotFoundError: No module named 'utils.parsers'
[2025-04-30T03:20:55.185+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:20:55.211+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.082 seconds
[2025-04-30T03:21:25.597+0000] {processor.py:186} INFO - Started process (PID=523) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:21:25.599+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T03:21:25.602+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:21:25.601+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:21:25.666+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:21:25.652+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 9, in <module>
    from clean_data import clean_data
  File "/opt/airflow/scripts/clean_data.py", line 5, in <module>
    from utils.parsers import parse_to_float
ModuleNotFoundError: No module named 'utils.parsers'
[2025-04-30T03:21:25.669+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:21:25.708+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.128 seconds
[2025-04-30T03:21:57.937+0000] {processor.py:186} INFO - Started process (PID=592) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:21:57.940+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T03:21:57.944+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:21:57.943+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:21:58.014+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:21:58.005+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 9, in <module>
    from clean_data import clean_data
  File "/opt/airflow/scripts/clean_data.py", line 5, in <module>
    from utils.parsers import parse_to_float
ModuleNotFoundError: No module named 'utils.parsers'
[2025-04-30T03:21:58.017+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:21:58.051+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.133 seconds
[2025-04-30T03:22:29.720+0000] {processor.py:186} INFO - Started process (PID=650) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:22:29.722+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T03:22:29.725+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:22:29.724+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:22:29.781+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:22:29.769+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 9, in <module>
    from clean_data import clean_data
  File "/opt/airflow/scripts/clean_data.py", line 5, in <module>
    from utils.parsers import parse_to_float
ModuleNotFoundError: No module named 'utils.parsers'
[2025-04-30T03:22:29.787+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:22:29.834+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.126 seconds
[2025-04-30T03:23:00.743+0000] {processor.py:186} INFO - Started process (PID=713) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:23:00.745+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T03:23:00.748+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:23:00.747+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:23:00.808+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:23:00.797+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 9, in <module>
    from clean_data import clean_data
  File "/opt/airflow/scripts/clean_data.py", line 5, in <module>
    from utils.parsers import parse_to_float
ModuleNotFoundError: No module named 'utils.parsers'
[2025-04-30T03:23:00.812+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:23:00.851+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.121 seconds
[2025-04-30T03:23:31.334+0000] {processor.py:186} INFO - Started process (PID=775) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:23:31.348+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T03:23:31.351+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:23:31.350+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:23:31.415+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:23:31.405+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 9, in <module>
    from clean_data import clean_data
  File "/opt/airflow/scripts/clean_data.py", line 5, in <module>
    from utils.parsers import parse_to_float
ModuleNotFoundError: No module named 'utils.parsers'
[2025-04-30T03:23:31.418+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:23:31.451+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.135 seconds
[2025-04-30T03:24:01.592+0000] {processor.py:186} INFO - Started process (PID=838) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:24:01.594+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T03:24:01.597+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:24:01.597+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:24:01.646+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:24:01.635+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 9, in <module>
    from clean_data import clean_data
  File "/opt/airflow/scripts/clean_data.py", line 5, in <module>
    from utils.parsers import parse_to_float
ModuleNotFoundError: No module named 'utils.parsers'
[2025-04-30T03:24:01.651+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:24:01.694+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.113 seconds
[2025-04-30T03:24:22.393+0000] {processor.py:186} INFO - Started process (PID=858) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:24:22.395+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T03:24:22.398+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:24:22.397+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:24:22.440+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:24:22.430+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 6, in <module>
    sys.path.append(os.path.dirname(__file__))
                    ^^
NameError: name 'os' is not defined. Did you forget to import 'os'
[2025-04-30T03:24:22.444+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:24:22.491+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.108 seconds
[2025-04-30T03:24:53.154+0000] {processor.py:186} INFO - Started process (PID=922) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:24:53.156+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T03:24:53.159+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:24:53.158+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:24:53.189+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:24:53.180+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 6, in <module>
    sys.path.append(os.path.dirname(__file__))
                    ^^
NameError: name 'os' is not defined. Did you forget to import 'os'
[2025-04-30T03:24:53.192+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:24:53.225+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.080 seconds
[2025-04-30T03:25:23.344+0000] {processor.py:186} INFO - Started process (PID=986) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:25:23.346+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T03:25:23.350+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:25:23.349+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:25:23.369+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:25:23.364+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 6, in <module>
    sys.path.append(os.path.dirname(__file__))
                    ^^
NameError: name 'os' is not defined. Did you forget to import 'os'
[2025-04-30T03:25:23.371+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:25:23.409+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.077 seconds
[2025-04-30T03:25:53.504+0000] {processor.py:186} INFO - Started process (PID=1049) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:25:53.505+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T03:25:53.507+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:25:53.507+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:25:53.527+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:25:53.523+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 6, in <module>
    sys.path.append(os.path.dirname(__file__))
                    ^^
NameError: name 'os' is not defined. Did you forget to import 'os'
[2025-04-30T03:25:53.530+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:25:53.557+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.062 seconds
[2025-04-30T03:26:23.722+0000] {processor.py:186} INFO - Started process (PID=1113) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:26:23.723+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T03:26:23.725+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:26:23.724+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:26:23.744+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:26:23.739+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 6, in <module>
    sys.path.append(os.path.dirname(__file__))
                    ^^
NameError: name 'os' is not defined. Did you forget to import 'os'
[2025-04-30T03:26:23.747+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:26:23.782+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.069 seconds
[2025-04-30T03:26:33.465+0000] {processor.py:186} INFO - Started process (PID=1133) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:26:33.473+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T03:26:33.476+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:26:33.475+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:26:33.555+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:26:33.546+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 10, in <module>
    from clean_data import clean_data
  File "/opt/airflow/scripts/clean_data.py", line 5, in <module>
    from utils.parsers import parse_to_float
ModuleNotFoundError: No module named 'utils.parsers'
[2025-04-30T03:26:33.558+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:26:33.589+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.137 seconds
[2025-04-30T03:27:03.747+0000] {processor.py:186} INFO - Started process (PID=1197) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:27:03.749+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T03:27:03.751+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:27:03.750+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:27:03.794+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:27:03.786+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 10, in <module>
    from clean_data import clean_data
  File "/opt/airflow/scripts/clean_data.py", line 5, in <module>
    from utils.parsers import parse_to_float
ModuleNotFoundError: No module named 'utils.parsers'
[2025-04-30T03:27:03.797+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:27:03.823+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.084 seconds
[2025-04-30T03:27:34.206+0000] {processor.py:186} INFO - Started process (PID=1261) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:27:34.208+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T03:27:34.211+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:27:34.211+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:27:34.286+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:27:34.277+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 10, in <module>
    from clean_data import clean_data
  File "/opt/airflow/scripts/clean_data.py", line 5, in <module>
    from utils.parsers import parse_to_float
ModuleNotFoundError: No module named 'utils.parsers'
[2025-04-30T03:27:34.290+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:27:34.327+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.132 seconds
[2025-04-30T03:28:04.663+0000] {processor.py:186} INFO - Started process (PID=1323) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:28:04.665+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T03:28:04.667+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:28:04.667+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:28:04.713+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:28:04.705+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 10, in <module>
    from clean_data import clean_data
  File "/opt/airflow/scripts/clean_data.py", line 5, in <module>
    from utils.parsers import parse_to_float
ModuleNotFoundError: No module named 'utils.parsers'
[2025-04-30T03:28:04.716+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:28:04.742+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.088 seconds
[2025-04-30T03:28:34.860+0000] {processor.py:186} INFO - Started process (PID=1386) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:28:34.861+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T03:28:34.865+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:28:34.864+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:28:34.973+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:28:34.961+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 10, in <module>
    from clean_data import clean_data
  File "/opt/airflow/scripts/clean_data.py", line 7, in <module>
    from utils.parsers import parse_to_float
ModuleNotFoundError: No module named 'utils.parsers'
[2025-04-30T03:28:34.979+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:28:35.075+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.227 seconds
[2025-04-30T03:39:55.214+0000] {processor.py:186} INFO - Started process (PID=74) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:39:55.223+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T03:39:55.227+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:39:55.226+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:39:55.362+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:39:55.298+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 10, in <module>
    from clean_data import clean_data
  File "/opt/airflow/scripts/clean_data.py", line 7, in <module>
    from utils.parsers import parse_to_float
ModuleNotFoundError: No module named 'utils.parsers'
[2025-04-30T03:39:55.366+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:39:55.423+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.223 seconds
[2025-04-30T03:40:26.713+0000] {processor.py:186} INFO - Started process (PID=139) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:40:26.715+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T03:40:26.724+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:40:26.724+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:40:26.975+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:40:26.939+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 10, in <module>
    from clean_data import clean_data
  File "/opt/airflow/scripts/clean_data.py", line 7, in <module>
    from utils.parsers import parse_to_float
ModuleNotFoundError: No module named 'utils.parsers'
[2025-04-30T03:40:26.980+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:40:27.042+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.350 seconds
[2025-04-30T03:40:57.453+0000] {processor.py:186} INFO - Started process (PID=200) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:40:57.457+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T03:40:57.473+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:40:57.472+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:40:57.594+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:40:57.578+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 10, in <module>
    from clean_data import clean_data
  File "/opt/airflow/scripts/clean_data.py", line 7, in <module>
    from utils.parsers import parse_to_float
ModuleNotFoundError: No module named 'utils.parsers'
[2025-04-30T03:40:57.598+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:40:57.652+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.215 seconds
[2025-04-30T03:41:27.987+0000] {processor.py:186} INFO - Started process (PID=265) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:41:27.989+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T03:41:27.992+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:41:27.992+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:41:28.034+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:41:28.025+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 10, in <module>
    from clean_data import clean_data
  File "/opt/airflow/scripts/clean_data.py", line 7, in <module>
    from utils.parsers import parse_to_float
ModuleNotFoundError: No module named 'utils.parsers'
[2025-04-30T03:41:28.037+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:41:28.068+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.089 seconds
[2025-04-30T03:41:58.313+0000] {processor.py:186} INFO - Started process (PID=329) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:41:58.315+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T03:41:58.319+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:41:58.318+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:41:58.360+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:41:58.353+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 10, in <module>
    from clean_data import clean_data
  File "/opt/airflow/scripts/clean_data.py", line 7, in <module>
    from utils.parsers import parse_to_float
ModuleNotFoundError: No module named 'utils.parsers'
[2025-04-30T03:41:58.363+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:41:58.395+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.090 seconds
[2025-04-30T03:42:28.487+0000] {processor.py:186} INFO - Started process (PID=394) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:42:28.489+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T03:42:28.492+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:42:28.492+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:42:28.536+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:42:28.528+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 10, in <module>
    from clean_data import clean_data
  File "/opt/airflow/scripts/clean_data.py", line 7, in <module>
    from utils.parsers import parse_to_float
ModuleNotFoundError: No module named 'utils.parsers'
[2025-04-30T03:42:28.539+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:42:28.569+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.088 seconds
[2025-04-30T03:42:58.960+0000] {processor.py:186} INFO - Started process (PID=454) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:42:58.963+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T03:42:58.967+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:42:58.966+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:42:59.014+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:42:59.005+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 10, in <module>
    from clean_data import clean_data
  File "/opt/airflow/scripts/clean_data.py", line 7, in <module>
    from utils.parsers import parse_to_float
ModuleNotFoundError: No module named 'utils.parsers'
[2025-04-30T03:42:59.018+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:42:59.061+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.114 seconds
[2025-04-30T03:43:29.764+0000] {processor.py:186} INFO - Started process (PID=518) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:43:29.767+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T03:43:29.773+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:43:29.772+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:43:29.851+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:43:29.840+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 10, in <module>
    from clean_data import clean_data
  File "/opt/airflow/scripts/clean_data.py", line 7, in <module>
    from utils.parsers import parse_to_float
ModuleNotFoundError: No module named 'utils.parsers'
[2025-04-30T03:43:29.855+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:43:29.923+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.175 seconds
[2025-04-30T03:44:00.104+0000] {processor.py:186} INFO - Started process (PID=583) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:44:00.106+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T03:44:00.109+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:44:00.109+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:44:00.158+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:44:00.150+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 10, in <module>
    from clean_data import clean_data
  File "/opt/airflow/scripts/clean_data.py", line 7, in <module>
    from utils.parsers import parse_to_float
ModuleNotFoundError: No module named 'utils.parsers'
[2025-04-30T03:44:00.161+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:44:00.190+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.094 seconds
[2025-04-30T03:44:30.532+0000] {processor.py:186} INFO - Started process (PID=647) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:44:30.534+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T03:44:30.538+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:44:30.537+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:44:30.605+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:44:30.594+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 10, in <module>
    from clean_data import clean_data
  File "/opt/airflow/scripts/clean_data.py", line 7, in <module>
    from utils.parsers import parse_to_float
ModuleNotFoundError: No module named 'utils.parsers'
[2025-04-30T03:44:30.615+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:44:30.652+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.131 seconds
[2025-04-30T03:45:01.179+0000] {processor.py:186} INFO - Started process (PID=711) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:45:01.181+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T03:45:01.184+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:45:01.184+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:45:01.234+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:45:01.225+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 10, in <module>
    from clean_data import clean_data
  File "/opt/airflow/scripts/clean_data.py", line 7, in <module>
    from utils.parsers import parse_to_float
ModuleNotFoundError: No module named 'utils.parsers'
[2025-04-30T03:45:01.237+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:45:01.264+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.094 seconds
[2025-04-30T03:45:31.669+0000] {processor.py:186} INFO - Started process (PID=776) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:45:31.670+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T03:45:31.673+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:45:31.673+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:45:31.720+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:45:31.711+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 10, in <module>
    from clean_data import clean_data
  File "/opt/airflow/scripts/clean_data.py", line 7, in <module>
    from utils.parsers import parse_to_float
ModuleNotFoundError: No module named 'utils.parsers'
[2025-04-30T03:45:31.724+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:45:31.765+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.106 seconds
[2025-04-30T03:46:02.184+0000] {processor.py:186} INFO - Started process (PID=840) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:46:02.186+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T03:46:02.190+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:46:02.189+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:46:02.286+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:46:02.276+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 10, in <module>
    from clean_data import clean_data
  File "/opt/airflow/scripts/clean_data.py", line 7, in <module>
    from utils.parsers import parse_to_float
ModuleNotFoundError: No module named 'utils.parsers'
[2025-04-30T03:46:02.292+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:46:02.335+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.165 seconds
[2025-04-30T03:46:33.308+0000] {processor.py:186} INFO - Started process (PID=904) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:46:33.310+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T03:46:33.314+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:46:33.313+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:46:33.373+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:46:33.362+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 10, in <module>
    from clean_data import clean_data
  File "/opt/airflow/scripts/clean_data.py", line 7, in <module>
    from utils.parsers import parse_to_float
ModuleNotFoundError: No module named 'utils.parsers'
[2025-04-30T03:46:33.378+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:46:33.433+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.137 seconds
[2025-04-30T03:47:04.070+0000] {processor.py:186} INFO - Started process (PID=974) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:47:04.072+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T03:47:04.077+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:47:04.076+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:47:04.142+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:47:04.124+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 10, in <module>
    from clean_data import clean_data
  File "/opt/airflow/scripts/clean_data.py", line 7, in <module>
    from utils.parsers import parse_to_float
ModuleNotFoundError: No module named 'utils.parsers'
[2025-04-30T03:47:04.147+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:47:04.182+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.122 seconds
[2025-04-30T03:47:34.373+0000] {processor.py:186} INFO - Started process (PID=1037) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:47:34.375+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T03:47:34.378+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:47:34.377+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:47:34.420+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:47:34.412+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 10, in <module>
    from clean_data import clean_data
  File "/opt/airflow/scripts/clean_data.py", line 7, in <module>
    from utils.parsers import parse_to_float
ModuleNotFoundError: No module named 'utils.parsers'
[2025-04-30T03:47:34.422+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:47:34.447+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.080 seconds
[2025-04-30T03:48:04.958+0000] {processor.py:186} INFO - Started process (PID=1101) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:48:04.959+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T03:48:04.962+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:48:04.962+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:48:05.010+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:48:05.002+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 10, in <module>
    from clean_data import clean_data
  File "/opt/airflow/scripts/clean_data.py", line 7, in <module>
    from utils.parsers import parse_to_float
ModuleNotFoundError: No module named 'utils.parsers'
[2025-04-30T03:48:05.014+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:48:05.046+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.097 seconds
[2025-04-30T03:48:35.118+0000] {processor.py:186} INFO - Started process (PID=1165) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:48:35.121+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T03:48:35.125+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:48:35.125+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:48:35.167+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:48:35.159+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 10, in <module>
    from clean_data import clean_data
  File "/opt/airflow/scripts/clean_data.py", line 7, in <module>
    from utils.parsers import parse_to_float
ModuleNotFoundError: No module named 'utils.parsers'
[2025-04-30T03:48:35.170+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:48:35.199+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.091 seconds
[2025-04-30T03:49:05.787+0000] {processor.py:186} INFO - Started process (PID=1228) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:49:05.788+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T03:49:05.793+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:49:05.792+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:49:05.874+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:49:05.856+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 10, in <module>
    from clean_data import clean_data
  File "/opt/airflow/scripts/clean_data.py", line 7, in <module>
    from utils.parsers import parse_to_float
ModuleNotFoundError: No module named 'utils.parsers'
[2025-04-30T03:49:05.877+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:49:05.923+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.147 seconds
[2025-04-30T03:49:36.535+0000] {processor.py:186} INFO - Started process (PID=1289) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:49:36.545+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T03:49:36.565+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:49:36.565+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:49:36.672+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:49:36.653+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 10, in <module>
    from clean_data import clean_data
  File "/opt/airflow/scripts/clean_data.py", line 7, in <module>
    from utils.parsers import parse_to_float
ModuleNotFoundError: No module named 'utils.parsers'
[2025-04-30T03:49:36.677+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:49:36.751+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.227 seconds
[2025-04-30T03:52:12.466+0000] {processor.py:186} INFO - Started process (PID=67) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:52:12.469+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T03:52:12.478+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:52:12.475+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:52:12.571+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:52:12.555+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 10, in <module>
    from clean_data import clean_data
  File "/opt/airflow/scripts/clean_data.py", line 7, in <module>
    from utils.parsers import parse_to_float
ModuleNotFoundError: No module named 'utils.parsers'
[2025-04-30T03:52:12.578+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:52:12.618+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.166 seconds
[2025-04-30T03:52:43.243+0000] {processor.py:186} INFO - Started process (PID=131) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:52:43.245+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T03:52:43.251+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:52:43.250+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:52:43.304+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:52:43.296+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 10, in <module>
    from clean_data import clean_data
  File "/opt/airflow/scripts/clean_data.py", line 7, in <module>
    from utils.parsers import parse_to_float
ModuleNotFoundError: No module named 'utils.parsers'
[2025-04-30T03:52:43.307+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:52:43.345+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.115 seconds
[2025-04-30T03:53:13.700+0000] {processor.py:186} INFO - Started process (PID=195) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:53:13.703+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T03:53:13.708+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:53:13.707+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:53:13.858+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:53:13.810+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 10, in <module>
    from clean_data import clean_data
  File "/opt/airflow/scripts/clean_data.py", line 7, in <module>
    from utils.parsers import parse_to_float
ModuleNotFoundError: No module named 'utils.parsers'
[2025-04-30T03:53:13.891+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:53:13.969+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.282 seconds
[2025-04-30T03:53:44.771+0000] {processor.py:186} INFO - Started process (PID=259) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:53:44.773+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T03:53:44.777+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:53:44.776+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:53:44.827+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:53:44.817+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 10, in <module>
    from clean_data import clean_data
  File "/opt/airflow/scripts/clean_data.py", line 7, in <module>
    from utils.parsers import parse_to_float
ModuleNotFoundError: No module named 'utils.parsers'
[2025-04-30T03:53:44.830+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:53:44.861+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.099 seconds
[2025-04-30T03:54:15.002+0000] {processor.py:186} INFO - Started process (PID=322) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:54:15.004+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T03:54:15.009+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:54:15.008+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:54:15.065+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:54:15.055+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 10, in <module>
    from clean_data import clean_data
  File "/opt/airflow/scripts/clean_data.py", line 7, in <module>
    from utils.parsers import parse_to_float
ModuleNotFoundError: No module named 'utils.parsers'
[2025-04-30T03:54:15.069+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:54:15.150+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.155 seconds
[2025-04-30T03:54:45.370+0000] {processor.py:186} INFO - Started process (PID=386) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:54:45.371+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T03:54:45.375+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:54:45.374+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:54:45.416+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:54:45.409+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 10, in <module>
    from clean_data import clean_data
  File "/opt/airflow/scripts/clean_data.py", line 7, in <module>
    from utils.parsers import parse_to_float
ModuleNotFoundError: No module named 'utils.parsers'
[2025-04-30T03:54:45.419+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:54:45.453+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.091 seconds
[2025-04-30T03:55:15.602+0000] {processor.py:186} INFO - Started process (PID=450) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:55:15.605+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T03:55:15.613+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:55:15.612+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:55:15.755+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:55:15.735+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 10, in <module>
    from clean_data import clean_data
  File "/opt/airflow/scripts/clean_data.py", line 7, in <module>
    from utils.parsers import parse_to_float
ModuleNotFoundError: No module named 'utils.parsers'
[2025-04-30T03:55:15.761+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:55:15.855+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.273 seconds
[2025-04-30T03:55:46.158+0000] {processor.py:186} INFO - Started process (PID=514) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:55:46.161+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T03:55:46.167+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:55:46.166+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:55:46.268+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:55:46.259+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 10, in <module>
    from clean_data import clean_data
  File "/opt/airflow/scripts/clean_data.py", line 7, in <module>
    from utils.parsers import parse_to_float
ModuleNotFoundError: No module named 'utils.parsers'
[2025-04-30T03:55:46.271+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:55:46.319+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.173 seconds
[2025-04-30T03:59:07.530+0000] {processor.py:186} INFO - Started process (PID=70) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:59:07.544+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T03:59:07.572+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:59:07.571+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:59:07.692+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:59:07.680+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 10, in <module>
    from clean_data import clean_data
  File "/opt/airflow/scripts/clean_data.py", line 7, in <module>
    from utils.parsers import parse_to_float
ModuleNotFoundError: No module named 'utils.parsers'
[2025-04-30T03:59:07.695+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:59:07.809+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.302 seconds
[2025-04-30T03:59:38.456+0000] {processor.py:186} INFO - Started process (PID=134) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:59:38.458+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T03:59:38.463+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:59:38.462+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:59:38.531+0000] {logging_mixin.py:190} INFO - [2025-04-30T03:59:38.521+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 10, in <module>
    from clean_data import clean_data
  File "/opt/airflow/scripts/clean_data.py", line 7, in <module>
    from utils.parsers import parse_to_float
ModuleNotFoundError: No module named 'utils.parsers'
[2025-04-30T03:59:38.536+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T03:59:38.577+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.135 seconds
[2025-04-30T04:00:08.837+0000] {processor.py:186} INFO - Started process (PID=198) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:00:08.838+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T04:00:08.843+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:00:08.842+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:00:08.898+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:00:08.887+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 10, in <module>
    from clean_data import clean_data
  File "/opt/airflow/scripts/clean_data.py", line 7, in <module>
    from utils.parsers import parse_to_float
ModuleNotFoundError: No module named 'utils.parsers'
[2025-04-30T04:00:08.902+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:00:08.942+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.113 seconds
[2025-04-30T04:00:39.692+0000] {processor.py:186} INFO - Started process (PID=262) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:00:39.693+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T04:00:39.697+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:00:39.696+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:00:39.744+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:00:39.735+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 10, in <module>
    from clean_data import clean_data
  File "/opt/airflow/scripts/clean_data.py", line 7, in <module>
    from utils.parsers import parse_to_float
ModuleNotFoundError: No module named 'utils.parsers'
[2025-04-30T04:00:39.748+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:00:39.792+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.109 seconds
[2025-04-30T04:01:09.920+0000] {processor.py:186} INFO - Started process (PID=325) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:01:09.921+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T04:01:09.925+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:01:09.925+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:01:09.958+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:01:09.952+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 10, in <module>
    from clean_data import clean_data
  File "/opt/airflow/scripts/clean_data.py", line 7, in <module>
    from utils.parsers import parse_to_float
ModuleNotFoundError: No module named 'utils.parsers'
[2025-04-30T04:01:09.961+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:01:09.985+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.072 seconds
[2025-04-30T04:01:40.121+0000] {processor.py:186} INFO - Started process (PID=389) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:01:40.123+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T04:01:40.130+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:01:40.128+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:01:40.205+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:01:40.192+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 10, in <module>
    from clean_data import clean_data
  File "/opt/airflow/scripts/clean_data.py", line 7, in <module>
    from utils.parsers import parse_to_float
ModuleNotFoundError: No module named 'utils.parsers'
[2025-04-30T04:01:40.209+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:01:40.262+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.151 seconds
[2025-04-30T04:02:11.288+0000] {processor.py:186} INFO - Started process (PID=453) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:02:11.290+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T04:02:11.296+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:02:11.295+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:02:11.345+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:02:11.335+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 10, in <module>
    from clean_data import clean_data
  File "/opt/airflow/scripts/clean_data.py", line 7, in <module>
    from utils.parsers import parse_to_float
ModuleNotFoundError: No module named 'utils.parsers'
[2025-04-30T04:02:11.348+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:02:11.376+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.096 seconds
[2025-04-30T04:02:41.605+0000] {processor.py:186} INFO - Started process (PID=517) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:02:41.606+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T04:02:41.612+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:02:41.611+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:02:41.673+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:02:41.662+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 10, in <module>
    from clean_data import clean_data
  File "/opt/airflow/scripts/clean_data.py", line 7, in <module>
    from utils.parsers import parse_to_float
ModuleNotFoundError: No module named 'utils.parsers'
[2025-04-30T04:02:41.678+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:02:41.741+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.146 seconds
[2025-04-30T04:03:11.878+0000] {processor.py:186} INFO - Started process (PID=579) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:03:11.880+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T04:03:11.884+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:03:11.882+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:03:11.926+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:03:11.918+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 10, in <module>
    from clean_data import clean_data
  File "/opt/airflow/scripts/clean_data.py", line 7, in <module>
    from utils.parsers import parse_to_float
ModuleNotFoundError: No module named 'utils.parsers'
[2025-04-30T04:03:11.929+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:03:11.958+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.086 seconds
[2025-04-30T04:03:42.515+0000] {processor.py:186} INFO - Started process (PID=642) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:03:42.516+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T04:03:42.520+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:03:42.519+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:03:42.556+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:03:42.550+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 10, in <module>
    from clean_data import clean_data
  File "/opt/airflow/scripts/clean_data.py", line 7, in <module>
    from utils.parsers import parse_to_float
ModuleNotFoundError: No module named 'utils.parsers'
[2025-04-30T04:03:42.559+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:03:42.595+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.086 seconds
[2025-04-30T04:04:12.948+0000] {processor.py:186} INFO - Started process (PID=706) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:04:12.950+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T04:04:12.955+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:04:12.954+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:04:13.011+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:04:13.001+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 10, in <module>
    from clean_data import clean_data
  File "/opt/airflow/scripts/clean_data.py", line 7, in <module>
    from utils.parsers import parse_to_float
ModuleNotFoundError: No module named 'utils.parsers'
[2025-04-30T04:04:13.015+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:04:13.050+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.111 seconds
[2025-04-30T04:04:43.651+0000] {processor.py:186} INFO - Started process (PID=770) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:04:43.654+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T04:04:43.660+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:04:43.659+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:04:43.724+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:04:43.714+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 10, in <module>
    from clean_data import clean_data
  File "/opt/airflow/scripts/clean_data.py", line 7, in <module>
    from utils.parsers import parse_to_float
ModuleNotFoundError: No module named 'utils.parsers'
[2025-04-30T04:04:43.728+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:04:43.773+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.138 seconds
[2025-04-30T04:05:14.124+0000] {processor.py:186} INFO - Started process (PID=834) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:05:14.126+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T04:05:14.129+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:05:14.128+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:05:14.173+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:05:14.164+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 10, in <module>
    from clean_data import clean_data
  File "/opt/airflow/scripts/clean_data.py", line 7, in <module>
    from utils.parsers import parse_to_float
ModuleNotFoundError: No module named 'utils.parsers'
[2025-04-30T04:05:14.177+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:05:14.203+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.085 seconds
[2025-04-30T04:05:44.339+0000] {processor.py:186} INFO - Started process (PID=899) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:05:44.341+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T04:05:44.346+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:05:44.345+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:05:44.407+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:05:44.401+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 10, in <module>
    from clean_data import clean_data
  File "/opt/airflow/scripts/clean_data.py", line 7, in <module>
    from utils.parsers import parse_to_float
ModuleNotFoundError: No module named 'utils.parsers'
[2025-04-30T04:05:44.410+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:05:44.436+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.112 seconds
[2025-04-30T04:06:15.541+0000] {processor.py:186} INFO - Started process (PID=964) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:06:15.543+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T04:06:15.549+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:06:15.549+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:06:15.645+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:06:15.637+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 10, in <module>
    from clean_data import clean_data
  File "/opt/airflow/scripts/clean_data.py", line 7, in <module>
    from utils.parsers import parse_to_float
ModuleNotFoundError: No module named 'utils.parsers'
[2025-04-30T04:06:15.648+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:06:15.679+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.153 seconds
[2025-04-30T04:06:46.058+0000] {processor.py:186} INFO - Started process (PID=1026) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:06:46.067+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T04:06:46.084+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:06:46.083+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:06:46.292+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:06:46.271+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 10, in <module>
    from clean_data import clean_data
  File "/opt/airflow/scripts/clean_data.py", line 7, in <module>
    from utils.parsers import parse_to_float
ModuleNotFoundError: No module named 'utils.parsers'
[2025-04-30T04:06:46.301+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:06:46.372+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.345 seconds
[2025-04-30T04:07:16.540+0000] {processor.py:186} INFO - Started process (PID=1089) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:07:16.541+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T04:07:16.545+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:07:16.544+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:07:16.600+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:07:16.583+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 10, in <module>
    from clean_data import clean_data
  File "/opt/airflow/scripts/clean_data.py", line 7, in <module>
    from utils.parsers import parse_to_float
ModuleNotFoundError: No module named 'utils.parsers'
[2025-04-30T04:07:16.603+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:07:16.638+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.107 seconds
[2025-04-30T04:07:47.805+0000] {processor.py:186} INFO - Started process (PID=1153) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:07:47.817+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T04:07:47.824+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:07:47.823+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:07:48.008+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:07:47.985+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 10, in <module>
    from clean_data import clean_data
  File "/opt/airflow/scripts/clean_data.py", line 7, in <module>
    from utils.parsers import parse_to_float
ModuleNotFoundError: No module named 'utils.parsers'
[2025-04-30T04:07:48.013+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:07:48.056+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.270 seconds
[2025-04-30T04:07:58.351+0000] {processor.py:186} INFO - Started process (PID=1162) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:07:58.353+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T04:07:58.360+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:07:58.359+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:07:58.454+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:07:58.446+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 9, in <module>
    from clean_data import clean_data
  File "/opt/airflow/scripts/clean_data.py", line 7, in <module>
    from utils.parsers import parse_to_float
ModuleNotFoundError: No module named 'utils.parsers'
[2025-04-30T04:07:58.460+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:07:58.492+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.154 seconds
[2025-04-30T04:08:28.802+0000] {processor.py:186} INFO - Started process (PID=1226) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:08:28.804+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T04:08:28.813+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:08:28.812+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:08:28.899+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:08:28.885+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 10, in <module>
    from clean_data import clean_data
  File "/opt/airflow/scripts/clean_data.py", line 7, in <module>
    from utils.parsers import parse_to_float
ModuleNotFoundError: No module named 'utils.parsers'
[2025-04-30T04:08:28.902+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:08:28.932+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.138 seconds
[2025-04-30T04:08:59.302+0000] {processor.py:186} INFO - Started process (PID=1289) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:08:59.304+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T04:08:59.308+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:08:59.308+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:08:59.375+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:08:59.365+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 10, in <module>
    from clean_data import clean_data
  File "/opt/airflow/scripts/clean_data.py", line 7, in <module>
    from utils.parsers import parse_to_float
ModuleNotFoundError: No module named 'utils.parsers'
[2025-04-30T04:08:59.383+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:08:59.443+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.159 seconds
[2025-04-30T04:09:29.677+0000] {processor.py:186} INFO - Started process (PID=1353) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:09:29.680+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T04:09:29.683+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:09:29.683+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:09:29.753+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:09:29.741+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 10, in <module>
    from clean_data import clean_data
  File "/opt/airflow/scripts/clean_data.py", line 7, in <module>
    from utils.parsers import parse_to_float
ModuleNotFoundError: No module named 'utils.parsers'
[2025-04-30T04:09:29.758+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:09:29.809+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.143 seconds
[2025-04-30T04:10:00.609+0000] {processor.py:186} INFO - Started process (PID=1415) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:10:00.611+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T04:10:00.615+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:10:00.615+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:10:00.668+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:10:00.658+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 10, in <module>
    from clean_data import clean_data
  File "/opt/airflow/scripts/clean_data.py", line 7, in <module>
    from utils.parsers import parse_to_float
ModuleNotFoundError: No module named 'utils.parsers'
[2025-04-30T04:10:00.672+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:10:00.715+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.119 seconds
[2025-04-30T04:10:31.497+0000] {processor.py:186} INFO - Started process (PID=1479) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:10:31.499+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T04:10:31.505+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:10:31.504+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:10:31.659+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:10:31.647+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 10, in <module>
    from clean_data import clean_data
  File "/opt/airflow/scripts/clean_data.py", line 7, in <module>
    from utils.parsers import parse_to_float
ModuleNotFoundError: No module named 'utils.parsers'
[2025-04-30T04:10:31.665+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:10:31.703+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.220 seconds
[2025-04-30T04:11:01.924+0000] {processor.py:186} INFO - Started process (PID=1543) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:11:01.931+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T04:11:01.943+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:11:01.942+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:11:02.210+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:11:02.183+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 10, in <module>
    from clean_data import clean_data
  File "/opt/airflow/scripts/clean_data.py", line 7, in <module>
    from utils.parsers import parse_to_float
ModuleNotFoundError: No module named 'utils.parsers'
[2025-04-30T04:11:02.216+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:11:02.279+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.371 seconds
[2025-04-30T04:11:32.478+0000] {processor.py:186} INFO - Started process (PID=1607) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:11:32.480+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T04:11:32.485+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:11:32.484+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:11:32.563+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:11:32.552+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 10, in <module>
    from clean_data import clean_data
  File "/opt/airflow/scripts/clean_data.py", line 7, in <module>
    from utils.parsers import parse_to_float
ModuleNotFoundError: No module named 'utils.parsers'
[2025-04-30T04:11:32.568+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:11:32.612+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.144 seconds
[2025-04-30T04:12:03.126+0000] {processor.py:186} INFO - Started process (PID=1672) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:12:03.132+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T04:12:03.138+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:12:03.137+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:12:03.313+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:12:03.296+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 10, in <module>
    from clean_data import clean_data
  File "/opt/airflow/scripts/clean_data.py", line 7, in <module>
    from utils.parsers import parse_to_float
ModuleNotFoundError: No module named 'utils.parsers'
[2025-04-30T04:12:03.319+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:12:03.367+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.256 seconds
[2025-04-30T04:12:33.670+0000] {processor.py:186} INFO - Started process (PID=1736) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:12:33.680+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T04:12:33.693+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:12:33.692+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:12:33.829+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:12:33.812+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 10, in <module>
    from clean_data import clean_data
  File "/opt/airflow/scripts/clean_data.py", line 7, in <module>
    from utils.parsers import parse_to_float
ModuleNotFoundError: No module named 'utils.parsers'
[2025-04-30T04:12:33.833+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:12:33.895+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.246 seconds
[2025-04-30T04:18:21.890+0000] {processor.py:186} INFO - Started process (PID=71) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:18:21.898+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T04:18:21.912+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:18:21.911+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:18:22.122+0000] {processor.py:925} INFO - DAG(s) 'etl_csv_pipeline_v2' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:18:23.581+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:18:23.580+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-30T04:18:23.639+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:18:23.636+0000] {dag.py:4180} INFO - Setting next_dagrun for etl_csv_pipeline_v2 to None, run_after=None
[2025-04-30T04:18:23.831+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 1.962 seconds
[2025-04-30T04:18:54.209+0000] {processor.py:186} INFO - Started process (PID=136) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:18:54.212+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T04:18:54.240+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:18:54.239+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:18:54.833+0000] {processor.py:925} INFO - DAG(s) 'etl_csv_pipeline_v2' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:18:55.115+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:18:55.115+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-30T04:18:55.279+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:18:55.278+0000] {dag.py:4180} INFO - Setting next_dagrun for etl_csv_pipeline_v2 to None, run_after=None
[2025-04-30T04:18:55.374+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 1.198 seconds
[2025-04-30T04:19:25.572+0000] {processor.py:186} INFO - Started process (PID=200) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:19:25.573+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T04:19:25.578+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:19:25.577+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:19:25.689+0000] {processor.py:925} INFO - DAG(s) 'etl_csv_pipeline_v2' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:19:25.732+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:19:25.732+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-30T04:19:25.781+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:19:25.780+0000] {dag.py:4180} INFO - Setting next_dagrun for etl_csv_pipeline_v2 to None, run_after=None
[2025-04-30T04:19:25.833+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.270 seconds
[2025-04-30T04:19:56.060+0000] {processor.py:186} INFO - Started process (PID=264) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:19:56.062+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T04:19:56.066+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:19:56.066+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:19:56.165+0000] {processor.py:925} INFO - DAG(s) 'etl_csv_pipeline_v2' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:19:56.218+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:19:56.215+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-30T04:19:56.276+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:19:56.275+0000] {dag.py:4180} INFO - Setting next_dagrun for etl_csv_pipeline_v2 to None, run_after=None
[2025-04-30T04:19:56.337+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.290 seconds
[2025-04-30T04:20:26.646+0000] {processor.py:186} INFO - Started process (PID=328) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:20:26.648+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T04:20:26.651+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:20:26.651+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:20:26.770+0000] {processor.py:925} INFO - DAG(s) 'etl_csv_pipeline_v2' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:20:26.824+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:20:26.823+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-30T04:20:26.860+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:20:26.860+0000] {dag.py:4180} INFO - Setting next_dagrun for etl_csv_pipeline_v2 to None, run_after=None
[2025-04-30T04:20:26.898+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.264 seconds
[2025-04-30T04:20:57.863+0000] {processor.py:186} INFO - Started process (PID=391) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:20:57.866+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T04:20:57.874+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:20:57.873+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:20:58.124+0000] {processor.py:925} INFO - DAG(s) 'etl_csv_pipeline_v2' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:20:58.177+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:20:58.177+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-30T04:20:58.247+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:20:58.246+0000] {dag.py:4180} INFO - Setting next_dagrun for etl_csv_pipeline_v2 to None, run_after=None
[2025-04-30T04:20:58.362+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.518 seconds
[2025-04-30T04:21:28.649+0000] {processor.py:186} INFO - Started process (PID=455) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:21:28.651+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T04:21:28.655+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:21:28.655+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:21:28.731+0000] {processor.py:925} INFO - DAG(s) 'etl_csv_pipeline_v2' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:21:28.767+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:21:28.767+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-30T04:21:28.815+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:21:28.815+0000] {dag.py:4180} INFO - Setting next_dagrun for etl_csv_pipeline_v2 to None, run_after=None
[2025-04-30T04:21:28.860+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.221 seconds
[2025-04-30T04:21:59.467+0000] {processor.py:186} INFO - Started process (PID=519) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:21:59.473+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T04:21:59.489+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:21:59.488+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:21:59.915+0000] {processor.py:925} INFO - DAG(s) 'etl_csv_pipeline_v2' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:22:00.011+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:22:00.000+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-30T04:22:00.122+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:22:00.121+0000] {dag.py:4180} INFO - Setting next_dagrun for etl_csv_pipeline_v2 to None, run_after=None
[2025-04-30T04:22:00.220+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.775 seconds
[2025-04-30T04:22:30.470+0000] {processor.py:186} INFO - Started process (PID=582) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:22:30.471+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T04:22:30.477+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:22:30.476+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:22:30.562+0000] {processor.py:925} INFO - DAG(s) 'etl_csv_pipeline_v2' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:22:30.614+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:22:30.613+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-30T04:22:30.666+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:22:30.665+0000] {dag.py:4180} INFO - Setting next_dagrun for etl_csv_pipeline_v2 to None, run_after=None
[2025-04-30T04:22:30.718+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.263 seconds
[2025-04-30T04:23:01.237+0000] {processor.py:186} INFO - Started process (PID=645) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:23:01.240+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T04:23:01.247+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:23:01.246+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:23:01.339+0000] {processor.py:925} INFO - DAG(s) 'etl_csv_pipeline_v2' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:23:01.378+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:23:01.378+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-30T04:23:01.409+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:23:01.408+0000] {dag.py:4180} INFO - Setting next_dagrun for etl_csv_pipeline_v2 to None, run_after=None
[2025-04-30T04:23:01.451+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.228 seconds
[2025-04-30T04:23:31.707+0000] {processor.py:186} INFO - Started process (PID=709) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:23:31.709+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T04:23:31.714+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:23:31.714+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:23:31.848+0000] {processor.py:925} INFO - DAG(s) 'etl_csv_pipeline_v2' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:23:31.902+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:23:31.901+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-30T04:23:31.930+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:23:31.930+0000] {dag.py:4180} INFO - Setting next_dagrun for etl_csv_pipeline_v2 to None, run_after=None
[2025-04-30T04:23:31.986+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.293 seconds
[2025-04-30T04:24:02.639+0000] {processor.py:186} INFO - Started process (PID=772) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:24:02.643+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T04:24:02.648+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:24:02.648+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:24:02.798+0000] {processor.py:925} INFO - DAG(s) 'etl_csv_pipeline_v2' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:24:02.871+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:24:02.870+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-30T04:24:02.903+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:24:02.902+0000] {dag.py:4180} INFO - Setting next_dagrun for etl_csv_pipeline_v2 to None, run_after=None
[2025-04-30T04:24:02.946+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.320 seconds
[2025-04-30T04:24:33.941+0000] {processor.py:186} INFO - Started process (PID=835) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:24:33.943+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T04:24:33.946+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:24:33.946+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:24:34.020+0000] {processor.py:925} INFO - DAG(s) 'etl_csv_pipeline_v2' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:24:34.052+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:24:34.052+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-30T04:24:34.078+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:24:34.077+0000] {dag.py:4180} INFO - Setting next_dagrun for etl_csv_pipeline_v2 to None, run_after=None
[2025-04-30T04:24:34.109+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.179 seconds
[2025-04-30T04:25:04.520+0000] {processor.py:186} INFO - Started process (PID=899) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:25:04.521+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T04:25:04.524+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:25:04.524+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:25:04.597+0000] {processor.py:925} INFO - DAG(s) 'etl_csv_pipeline_v2' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:25:04.627+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:25:04.627+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-30T04:25:04.651+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:25:04.651+0000] {dag.py:4180} INFO - Setting next_dagrun for etl_csv_pipeline_v2 to None, run_after=None
[2025-04-30T04:25:04.692+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.186 seconds
[2025-04-30T04:25:34.846+0000] {processor.py:186} INFO - Started process (PID=963) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:25:34.848+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T04:25:34.852+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:25:34.852+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:25:34.934+0000] {processor.py:925} INFO - DAG(s) 'etl_csv_pipeline_v2' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:25:34.968+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:25:34.967+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-30T04:25:34.994+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:25:34.993+0000] {dag.py:4180} INFO - Setting next_dagrun for etl_csv_pipeline_v2 to None, run_after=None
[2025-04-30T04:25:35.035+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.199 seconds
[2025-04-30T04:26:05.968+0000] {processor.py:186} INFO - Started process (PID=1028) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:26:05.970+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T04:26:05.973+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:26:05.973+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:26:06.054+0000] {processor.py:925} INFO - DAG(s) 'etl_csv_pipeline_v2' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:26:06.086+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:26:06.086+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-30T04:26:06.111+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:26:06.110+0000] {dag.py:4180} INFO - Setting next_dagrun for etl_csv_pipeline_v2 to None, run_after=None
[2025-04-30T04:26:06.146+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.186 seconds
[2025-04-30T04:26:36.311+0000] {processor.py:186} INFO - Started process (PID=1092) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:26:36.312+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T04:26:36.316+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:26:36.315+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:26:36.426+0000] {processor.py:925} INFO - DAG(s) 'etl_csv_pipeline_v2' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:26:36.459+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:26:36.459+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-30T04:26:36.485+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:26:36.484+0000] {dag.py:4180} INFO - Setting next_dagrun for etl_csv_pipeline_v2 to None, run_after=None
[2025-04-30T04:26:36.519+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.218 seconds
[2025-04-30T04:27:06.620+0000] {processor.py:186} INFO - Started process (PID=1156) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:27:06.621+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T04:27:06.624+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:27:06.624+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:27:06.689+0000] {processor.py:925} INFO - DAG(s) 'etl_csv_pipeline_v2' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:27:06.716+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:27:06.715+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-30T04:27:06.747+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:27:06.746+0000] {dag.py:4180} INFO - Setting next_dagrun for etl_csv_pipeline_v2 to None, run_after=None
[2025-04-30T04:27:06.864+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.252 seconds
[2025-04-30T04:27:36.931+0000] {processor.py:186} INFO - Started process (PID=1209) to work on /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:27:36.932+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-04-30T04:27:36.936+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:27:36.936+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:27:37.032+0000] {processor.py:925} INFO - DAG(s) 'etl_csv_pipeline_v2' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-04-30T04:27:37.066+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:27:37.066+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-30T04:27:37.096+0000] {logging_mixin.py:190} INFO - [2025-04-30T04:27:37.096+0000] {dag.py:4180} INFO - Setting next_dagrun for etl_csv_pipeline_v2 to None, run_after=None
[2025-04-30T04:27:37.141+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.220 seconds
